apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: spatter-pod
  name: wc-input
data:
  input.txt: |-
    w0 w1 w2 w3 w4 w5 w6 w7 w8 w9 w10 w11 w12 w13 w14 w15 w16 w17 w18 w19
    w0 w1 w2 w3 w4 w5 w6 w7 w8 w9 w10 w11 w12 w13 w14 w15 w16 w17 w18 w19
    w20 w21 w22 w23 w24 w25 w26 w27 w28 w29 w30 w31 w32 w33 w34 w35 w36 w37
    w20 w21 w22 w23 w24 w25 w26 w27 w28 w29 w30 w31 w32 w33 w34 w35 w36 w37
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: spatter-pod
  name: spatter-pod
spec:
  containers:
    - name: rank0
      image: localhost/spatter:latest
      imagePullPolicy: IfNotPresent
      args: ["/data/input.txt"]
      env:
        - name: SPATTER_RANK
          value: "0"
        - name: SPATTER_N
          value: "3"
        - name: SPATTER_PORT
          value: "18741"
        - name: SPATTER_BIND
          value: "127.0.0.1"
      volumeMounts:
        - name: data
          mountPath: /data
    - name: rank1
      image: localhost/spatter:latest
      imagePullPolicy: IfNotPresent
      args: ["/data/input.txt"]
      env:
        - name: SPATTER_RANK
          value: "1"
        - name: SPATTER_N
          value: "3"
        - name: SPATTER_PORT
          value: "18741"
      volumeMounts:
        - name: data
          mountPath: /data
    - name: rank2
      image: localhost/spatter:latest
      imagePullPolicy: IfNotPresent
      args: ["/data/input.txt"]
      env:
        - name: SPATTER_RANK
          value: "2"
        - name: SPATTER_N
          value: "3"
        - name: SPATTER_PORT
          value: "18741"
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      configMap:
        name: wc-input